# Generated by Django 4.1.1 on 2023-05-16 14:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/db/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/db/news/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('course_type', models.CharField(blank=True, max_length=200, null=True)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('catagory', models.CharField(default='graduate', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestedPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('number', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(default='', max_length=200)),
                ('instagram', models.CharField(default='', max_length=200)),
                ('facebook', models.CharField(default='', max_length=200)),
                ('about', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/db/workers/')),
                ('catagory', models.CharField(default='leaders', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UndergraduateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/db/news/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('course_type', models.CharField(blank=True, max_length=200, null=True)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('catagory', models.CharField(default='undergraduate', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('number', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(default='', max_length=200)),
                ('instagram', models.CharField(default='', max_length=200)),
                ('facebook', models.CharField(default='', max_length=200)),
                ('about', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/db/workers/')),
                ('catagory', models.CharField(default='staff', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_of_graduations', models.IntegerField()),
                ('number_of_professors', models.IntegerField()),
                ('number_of_housing', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('about_university_title', tinymce.models.HTMLField()),
                ('about_university_body', tinymce.models.HTMLField()),
                ('about_university_image', models.ImageField(upload_to='static/db/about_university/')),
                ('university_location', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.ManyToManyField(to='app.uniphone')),
                ('university_email', models.ManyToManyField(to='app.emailaddress')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('body', tinymce.models.HTMLField()),
                ('date_created', models.DateField()),
                ('image', models.ImageField(upload_to='static/db/news/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('news_catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newscatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('body', tinymce.models.HTMLField()),
                ('date_created', models.DateTimeField()),
                ('image', models.ImageField(upload_to='static/db/news/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.workers')),
            ],
        ),
    ]
