# Generated by Django 4.1.1 on 2023-05-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='status',
            name='university_email',
        ),
        migrations.DeleteModel(
            name='EmailAddress',
        ),
        migrations.DeleteModel(
            name='UniPhone',
        ),
    ]
