# Generated by Django 4.1.1 on 2023-06-19 12:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='about_university_title_ru',
            field=tinymce.models.HTMLField(default='salom'),
        ),
    ]
