# Generated by Django 4.1.1 on 2023-06-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedstudents',
            name='social_status_file',
            field=models.FileField(blank=True, null=True, upload_to='static/users/social_statuses'),
        ),
    ]
