# Generated by Django 4.1.1 on 2023-05-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emailaddress_uniphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='phone_number',
            field=models.ManyToManyField(to='app.uniphone'),
        ),
        migrations.AddField(
            model_name='status',
            name='university_email',
            field=models.ManyToManyField(to='app.emailaddress'),
        ),
    ]
