# Generated by Django 4.1.1 on 2023-05-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_article_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='news_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_catagory', to='app.newscatagory'),
        ),
    ]
