# Generated by Django 4.1.1 on 2023-05-27 11:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_options_alter_articlecatagory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaders',
            old_name='about',
            new_name='about_en',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='about',
            new_name='about_en',
        ),
        migrations.RemoveField(
            model_name='leaders',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='leaders',
            name='position',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='position',
        ),
        migrations.AddField(
            model_name='leaders',
            name='about_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaders',
            name='about_uz',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaders',
            name='fullname_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leaders',
            name='fullname_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leaders',
            name='fullname_uz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leaders',
            name='position_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leaders',
            name='position_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leaders',
            name='position_uz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workers',
            name='about_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='about_uz',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='fullname_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workers',
            name='fullname_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workers',
            name='fullname_uz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workers',
            name='position_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workers',
            name='position_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workers',
            name='position_uz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='catagory',
            field=models.CharField(default='leaders', max_length=200),
        ),
    ]
