# Generated by Django 4.1.1 on 2023-06-19 15:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_body_en_alter_article_body_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_ru',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_tr',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_uz',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_ru',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_tr',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_uz',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graduatecourse',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graduatecourse',
            name='course_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graduatecourse',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graduatecourse',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='about_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='about_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='about_tr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='about_uz',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='facebook',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='fullname_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='fullname_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='fullname_tr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='fullname_uz',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='instagram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='position_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='position_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='position_tr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='position_uz',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='telegram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='new',
            name='body_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='body_ru',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='body_tr',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='about_university_body_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='about_university_body_ru',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='about_university_body_tr',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='about_university_body_uz',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='about_university_title_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='about_university_title_ru',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='about_university_title_tr',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='about_university_title_uz',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='body_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='body_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='body_tr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='body_uz',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='course_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduatecourse',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='about_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='about_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='about_tr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='about_uz',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='facebook',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='fullname_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='fullname_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='fullname_tr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='fullname_uz',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='instagram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='position_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='position_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='position_tr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='position_uz',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='telegram',
            field=models.CharField(max_length=200),
        ),
    ]
