# Generated by Django 4.1.1 on 2023-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appliedstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedstudents',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
