# Generated by Django 4.1.1 on 2023-06-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_journal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='file',
            new_name='arxiv',
        ),
    ]
