# Generated by Django 4.1.1 on 2023-06-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_appliedstudents_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='rector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.leaders'),
        ),
    ]
