# Generated by Django 4.1.1 on 2023-06-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_file_journal_arxiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
