# Generated by Django 4.1.1 on 2023-06-06 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_appliedstudents_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedstudents',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
