# Generated by Django 4.1.1 on 2023-06-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_universitygallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitygallery',
            options={'verbose_name': 'University picture', 'verbose_name_plural': 'University Pictures'},
        ),
        migrations.AddField(
            model_name='appliedstudents',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.undergraduatecourse'),
        ),
    ]
