# Generated by Django 4.1.1 on 2023-06-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_appliedstudents_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedstudents',
            name='bot_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
