# Generated by Django 4.1.1 on 2023-06-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_appliedstudents_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedstudents',
            name='social_status',
            field=models.CharField(choices=[('', 'Ijtimoiy xolat'), ('Yoshlar daftari', 'Yoshlar daftari'), ('Ayollar daftari', 'Ayollar daftari'), ('Temir daftar', 'Temir daftar'), ("Yo'q", "Yo'q"), ('Boshqa', 'Boshqa')], max_length=200),
        ),
    ]
