# Generated by Django 4.1.1 on 2023-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_appliedstudents_social_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedstudents',
            name='language',
            field=models.CharField(blank=True, choices=[('', "O'qish tilini tanlang"), ('en', 'Ingliz'), ('uz', "O'zbek"), ('ru', 'Rus')], max_length=200, null=True),
        ),
    ]
