# Generated by Django 4.1.1 on 2023-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botadmin',
            name='user',
            field=models.ManyToManyField(related_name='bot_users', to='bot.botusers'),
        ),
    ]
